name: Continuous Integration

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Build and run unit tests
    env:
      BOOKSTORE_TESTS: ./Bookstore.Tests/Bookstore.Tests.csproj

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100-rc.2.20479.15
      - run: dotnet build ${{ env.BOOKSTORE_TESTS }}

      - name: Execute Unit Tests
        run: dotnet test ${{ env.BOOKSTORE_TESTS }} --verbosity minimal
